[Xorg_scrnsaverproto]
git-tree-sha1 = "f342c2aaf96824500b214d50a993782d812d0c8b"

    [[Xorg_scrnsaverproto.download]]
    sha256 = "b1ee248381ac166d6a83178ddcd4fb0c9dd20f0f115b3a06088bb0a674d7e976"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_scrnsaverproto_jll.jl/releases/download/Xorg_scrnsaverproto-v1.2.2+1/Xorg_scrnsaverproto.v1.2.2.any.tar.gz"
